-- ==============================================================
-- SuppPOS — Turso / libSQL baseline schema
-- Generic: contains NO client data. Safe for every new database.
--
-- Conventions (converted from the original PostgreSQL schema):
--   ids ............ TEXT (UUID generated by the server code)
--   money .......... INTEGER paise   (Rs 12.34 -> 1234)
--   tax rates ...... INTEGER basis points (18% -> 1800)
--   timestamps ..... TEXT ISO-8601 UTC  e.g. 2026-09-24T08:00:00.000Z
--   dates .......... TEXT YYYY-MM-DD
--   booleans ....... INTEGER 0/1 with CHECK
--   arrays / json .. TEXT holding JSON
-- ==============================================================

-- ============ users (replaces Supabase Auth) ============
CREATE TABLE users (
  id TEXT PRIMARY KEY NOT NULL,
  email TEXT NOT NULL COLLATE NOCASE UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ============ roles (was enum app_role) ============
CREATE TABLE user_roles (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('admin')),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE (user_id, role)
);

-- ============ profiles ============
CREATE TABLE profiles (
  id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  full_name TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ============ shop settings (singleton) ============
CREATE TABLE shop_settings (
  id TEXT PRIMARY KEY NOT NULL,
  singleton INTEGER NOT NULL DEFAULT 1 UNIQUE CHECK (singleton = 1),
  shop_name TEXT NOT NULL DEFAULT 'My Supplement Store',
  legal_name TEXT,
  address TEXT,
  phone TEXT,
  gstin TEXT,
  invoice_prefix TEXT NOT NULL DEFAULT 'INV',
  invoice_next_number INTEGER NOT NULL DEFAULT 1,
  invoice_number_padding INTEGER NOT NULL DEFAULT 6,
  invoice_include_year INTEGER NOT NULL DEFAULT 1 CHECK (invoice_include_year IN (0,1)),
  gst_enabled_by_default INTEGER NOT NULL DEFAULT 1 CHECK (gst_enabled_by_default IN (0,1)),
  prices_include_tax INTEGER NOT NULL DEFAULT 0 CHECK (prices_include_tax IN (0,1)),
  default_gst_rate INTEGER NOT NULL DEFAULT 1800,
  allowed_gst_rates TEXT NOT NULL DEFAULT '[0,500,1200,1800,2800]' CHECK (json_valid(allowed_gst_rates)),
  receipt_width TEXT NOT NULL DEFAULT '80mm' CHECK (receipt_width IN ('58mm','80mm')),
  receipt_footer_text TEXT NOT NULL DEFAULT 'Thank you! Visit again.',
  storage_limit_mb INTEGER NOT NULL DEFAULT 500,
  storage_warn_percent INTEGER NOT NULL DEFAULT 70,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ============ products ============
CREATE TABLE products (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  brand TEXT,
  category TEXT,
  sku TEXT,
  barcode TEXT,
  purchase_price INTEGER NOT NULL DEFAULT 0,
  selling_price INTEGER NOT NULL DEFAULT 0,
  tax_percent INTEGER NOT NULL DEFAULT 1800,
  current_stock INTEGER NOT NULL DEFAULT 0,
  reorder_level INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX products_sku_uniq ON products (lower(sku)) WHERE sku IS NOT NULL AND sku <> '';
CREATE UNIQUE INDEX products_barcode_uniq ON products (barcode) WHERE barcode IS NOT NULL AND barcode <> '';
CREATE INDEX products_name_idx ON products (lower(name));
CREATE INDEX products_active_cat_idx ON products (is_active, category);

-- ============ customers ============
CREATE TABLE customers (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX customers_phone_uniq ON customers (phone) WHERE phone IS NOT NULL AND phone <> '';
CREATE INDEX customers_name_idx ON customers (lower(name));

-- ============ suppliers ============
CREATE TABLE suppliers (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  phone TEXT,
  gstin TEXT,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ============ purchases ============
CREATE TABLE purchases (
  id TEXT PRIMARY KEY NOT NULL,
  supplier_id TEXT REFERENCES suppliers(id) ON DELETE RESTRICT,
  purchase_date TEXT NOT NULL DEFAULT (date('now')),
  invoice_ref TEXT,
  total_amount INTEGER NOT NULL DEFAULT 0,
  created_by TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX purchases_date_idx ON purchases (purchase_date DESC);

CREATE TABLE purchase_items (
  id TEXT PRIMARY KEY NOT NULL,
  purchase_id TEXT NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  purchase_price INTEGER NOT NULL DEFAULT 0,
  line_total INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX purchase_items_purchase_idx ON purchase_items (purchase_id);
CREATE INDEX purchase_items_product_idx ON purchase_items (product_id);

-- ============ invoices ============
-- discount_value: paise when discount_type='amount', basis points when 'percent'.
CREATE TABLE invoices (
  id TEXT PRIMARY KEY NOT NULL,
  invoice_number TEXT NOT NULL UNIQUE,
  invoice_date TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name_snapshot TEXT,
  customer_phone_snapshot TEXT,
  subtotal INTEGER NOT NULL DEFAULT 0,
  discount_type TEXT NOT NULL DEFAULT 'none' CHECK (discount_type IN ('none','percent','amount')),
  discount_value INTEGER NOT NULL DEFAULT 0,
  discount_amount INTEGER NOT NULL DEFAULT 0,
  gst_applied INTEGER NOT NULL DEFAULT 0 CHECK (gst_applied IN (0,1)),
  prices_include_tax INTEGER NOT NULL DEFAULT 0 CHECK (prices_include_tax IN (0,1)),
  taxable_amount INTEGER NOT NULL DEFAULT 0,
  tax_amount INTEGER NOT NULL DEFAULT 0,
  total_amount INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed','partially_returned','returned')),
  created_by TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX invoices_date_idx ON invoices (invoice_date DESC);
CREATE INDEX invoices_customer_idx ON invoices (customer_id);

CREATE TABLE invoice_items (
  id TEXT PRIMARY KEY NOT NULL,
  invoice_id TEXT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  product_id TEXT REFERENCES products(id) ON DELETE RESTRICT,
  product_name_snapshot TEXT NOT NULL,
  sku_snapshot TEXT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price INTEGER NOT NULL,
  cost_price_snapshot INTEGER NOT NULL DEFAULT 0,
  tax_percent INTEGER NOT NULL DEFAULT 0,
  line_discount_amount INTEGER NOT NULL DEFAULT 0,
  taxable_amount INTEGER NOT NULL DEFAULT 0,
  tax_amount INTEGER NOT NULL DEFAULT 0,
  line_total INTEGER NOT NULL DEFAULT 0,
  returned_quantity INTEGER NOT NULL DEFAULT 0,
  CHECK (returned_quantity >= 0 AND returned_quantity <= quantity)
);
CREATE INDEX invoice_items_invoice_idx ON invoice_items (invoice_id);
CREATE INDEX invoice_items_product_idx ON invoice_items (product_id);

CREATE TABLE payments (
  id TEXT PRIMARY KEY NOT NULL,
  invoice_id TEXT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  method TEXT NOT NULL CHECK (method IN ('cash','card','upi')),
  amount INTEGER NOT NULL,
  reference TEXT,
  paid_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX payments_invoice_idx ON payments (invoice_id);
CREATE INDEX payments_paid_at_idx ON payments (paid_at DESC);

-- ============ returns ============
CREATE TABLE sales_returns (
  id TEXT PRIMARY KEY NOT NULL,
  return_number TEXT NOT NULL UNIQUE,
  invoice_id TEXT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  return_date TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  total_refund INTEGER NOT NULL DEFAULT 0,
  refund_method TEXT NOT NULL DEFAULT 'cash' CHECK (refund_method IN ('cash','card','upi','adjustment')),
  reason TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX sales_returns_invoice_idx ON sales_returns (invoice_id);
CREATE INDEX sales_returns_date_idx ON sales_returns (return_date DESC);

CREATE TABLE sales_return_items (
  id TEXT PRIMARY KEY NOT NULL,
  return_id TEXT NOT NULL REFERENCES sales_returns(id) ON DELETE CASCADE,
  invoice_item_id TEXT NOT NULL REFERENCES invoice_items(id) ON DELETE RESTRICT,
  product_id TEXT REFERENCES products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price INTEGER NOT NULL DEFAULT 0,
  refund_amount INTEGER NOT NULL DEFAULT 0,
  taxable_amount INTEGER NOT NULL DEFAULT 0,
  tax_amount INTEGER NOT NULL DEFAULT 0,
  cost_amount INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX sales_return_items_return_idx ON sales_return_items (return_id);

-- ============ stock movements ============
CREATE TABLE stock_movements (
  id TEXT PRIMARY KEY NOT NULL,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  movement_type TEXT NOT NULL CHECK (movement_type IN ('purchase','sale','return','adjustment','import')),
  quantity_change INTEGER NOT NULL,
  resulting_stock INTEGER NOT NULL,
  reference_table TEXT,
  reference_id TEXT,
  note TEXT,
  created_by TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX stock_movements_product_idx ON stock_movements (product_id, created_at DESC);
CREATE INDEX stock_movements_created_idx ON stock_movements (created_at DESC);
CREATE INDEX stock_movements_ref_idx ON stock_movements (reference_table, reference_id);

-- ============ import batches (temporary data) ============
CREATE TABLE import_batches (
  id TEXT PRIMARY KEY NOT NULL,
  filename TEXT,
  row_count INTEGER NOT NULL DEFAULT 0,
  success_count INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  errors TEXT CHECK (errors IS NULL OR json_valid(errors)),
  status TEXT NOT NULL DEFAULT 'completed',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- ============ updated_at triggers (was touch_updated_at) ============
CREATE TRIGGER products_touch AFTER UPDATE ON products FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE products SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER customers_touch AFTER UPDATE ON customers FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE customers SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER shop_settings_touch AFTER UPDATE ON shop_settings FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE shop_settings SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

CREATE TRIGGER users_touch AFTER UPDATE ON users FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE users SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
END;

-- ============ only seed: generic default settings row ============
INSERT INTO shop_settings (id, singleton) VALUES (lower(hex(randomblob(16))), 1);
